include:
  - board: nice_nano_v2
    shield: handzilla_left
  - board: nice_nano_v2
    shield: handzilla_right
  - board: nice_nano_v2
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: handzilla_dongle
